name: Generator

on:
  workflow_dispatch:

jobs:
  generate-primes:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Run script
        run: |
          ./do.sh
          ./do.sh
          ./do.sh
          ./do.sh
          ./do.sh

      - name: Commit and push generated files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add *.txt
          git commit -m "Update strings"
          git push

      - name: Trigger workflow
        run: |
          sleep 5
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.WORKFLOW_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/generator.yml/dispatches \
            -d '{"ref":"main"}'
